/* D2 full build — bake every route to static HTML. A rebuild accompanies every pull.

   Routes (all knowable from the data):
     /jobs/{slug}-{job_number}/   one per job          JobPosting JSON-LD (live jobs only)
     /jobs/                       all-jobs index        no JSON-LD
     /{state}/                    per state present     no JSON-LD
     /{state}/{category}/         per category present  no JSON-LD
     /                            landing               no JSON-LD

   JSON-LD is emitted only on a LIVE job page: an expired job (the pull removed it) shows
   "no longer accepting applications", so a JobPosting there would contradict the page
   (markup–page parity). Reads Supabase via the publishable key. Baked mobile-first.

   Run: npm run build   (from prerender/) */
import { createServer } from "node:http";
import { readFile, writeFile, mkdir, stat, rm, cp, copyFile, readdir } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { extname, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer-core";
import { jobPostingLd, jobPostingScript } from "../noprobjobs/data/jobPosting.js";
import { jobPath, browsePath, CAT_SLUG, STATE_SLUG, backTo } from "../noprobjobs/data/routes.js";
import * as PM from "../noprobjobs/data/pageMeta.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SITE = join(HERE, "..", "noprobjobs");
const OUT = join(HERE, "out");
const COUNTRY = JSON.parse(readFileSync(join(HERE, "..", "config", "source_country.json"), "utf8"));
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const REST = "https://eyatyzatcmjnmazmaghd.supabase.co/rest/v1";
const KEY = "sb_publishable_T49bDaIS8d7-AhQ8SsFU0g_ZA55yNQE";
const PORT = 8795;
const CONC = 6;                                     // concurrent Chrome pages
const SITE_URL = (process.env.SITE_URL || "https://noprobjobs.com").replace(/\/$/, "");   // canonical + OG + sitemap base
const MOBILE = { width: 412, height: 915, deviceScaleFactor: 2, isMobile: true, hasTouch: true };
// Change #2: the Washington lander — a landing-page clone (served from index.html, so it runs
// landing.js) that differs only in its headline. Baked as its own route; excluded from the
// state-browse machinery entirely (no filtering, no state param). Trailing slash to match how
// every other baked route is written and how trailingSlash serves it.
const WA_LANDER = "/washington-jobs/";
const MIME = { ".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".css":"text/css",
  ".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2",".map":"application/json" };

const WAIT = {
  job: "document.querySelectorAll('[data-desc-html]').length >= 2 && !!document.querySelector('h1')",
  browse: "document.querySelectorAll(\"[role='list'] > *\").length > 0",
  landing: "document.getElementById('root') && document.getElementById('root').children.length > 0",
};

function serve(){
  return createServer(async (req, res) => {
    let p = decodeURIComponent(req.url.split("?")[0]);
    try {
      if (p !== "/" && existsSync(join(SITE, p)) && (await stat(join(SITE, p))).isFile()) {
        res.writeHead(200, { "content-type": MIME[extname(p)] || "application/octet-stream" });
        return res.end(await readFile(join(SITE, p)));
      }
      // "/" and the Washington lander are the landing SPA (index.html → landing.js); every
      // other virtual path is the board SPA (board.html → board.js).
      const isLanding = p === "/" || p.replace(/\/+$/, "") === WA_LANDER.replace(/\/+$/, "");
      res.writeHead(200, { "content-type": "text/html" });
      res.end(await readFile(join(SITE, isLanding ? "index.html" : "board.html")));
    } catch (e) { res.writeHead(500); res.end(String(e)); }
  });
}

async function fetchAll(path){
  const r = await fetch(REST + path, { headers: { apikey: KEY, Authorization: "Bearer " + KEY } });
  if (!r.ok) throw new Error(path + " -> " + r.status);
  return r.json();
}

async function writeBaked(routePath, html){
  const dir = join(OUT, routePath.replace(/\/$/, ""));
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "index.html"), html, "utf8");
}

// Vercel Edge Middleware (self-contained, no imports so it bundles as a plain edge fn):
// job lifecycle at the edge. expired -> 410 + a message and a route back; retired/unknown
// job URL -> the named 404; live -> fall through to the baked static page.
function middlewareSource(expiredBack, live){
  const head = "// Generated by prerender/build.mjs — do not edit. Job lifecycle at the edge.\n"
    + "const EXPIRED = " + JSON.stringify(expiredBack) + ";\n"
    + "const LIVE = new Set(" + JSON.stringify(live) + ");\n"
    + "export const config = { matcher: '/jobs/:path*' };\n";
  const body = [
    "function gone(info){",
    "  var back = info.back || '/jobs/';",
    "  var q = 'alerts=1' + (info.cat ? '&cat=' + encodeURIComponent(info.cat) : '') + (info.city ? '&city=' + encodeURIComponent(info.city) : '');",
    "  var alertsUrl = back + (back.indexOf('?') < 0 ? '?' : '&') + q;",
    "  return '<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">'",
    "    + '<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">'",
    "    + '<title>Job no longer available — NoProbJobs.com</title>'",
    "    + '<style>body{font-family:system-ui,-apple-system,\"Segoe UI\",sans-serif;background:#f7f9fc;margin:0;color:#132a4a}main{max-width:560px;margin:0 auto;padding:72px 22px}.badge{display:inline-block;padding:4px 10px;border-radius:3px;background:#c8102e;color:#fff;font-size:12px;font-weight:700;letter-spacing:.04em;text-transform:uppercase}h1{font-size:30px;line-height:1.14;margin:18px 0 10px;letter-spacing:-.01em}p{font-size:16.5px;line-height:1.6;color:#5a6b83;margin:0 0 22px;max-width:46ch}a.cta{display:inline-flex;align-items:center;min-height:46px;padding:0 20px;border-radius:3px;background:#c8102e;color:#fff;text-decoration:none;font-weight:700;font-size:15.5px}a.alt{display:inline-block;margin-left:14px;color:#132a4a;font-weight:600;font-size:15px}</style>'",
    "    + '</head><body><main><span class=\"badge\">No experience needed</span>'",
    "    + '<h1>Unfortunately, this job is no longer available.</h1>'",
    "    + '<p>Sign up for job alerts and we\\'ll email you when similar jobs are posted.</p>'",
    "    + '<a class=\"cta\" href=\"' + alertsUrl + '\">Get job alerts</a>'",
    "    + '<a class=\"alt\" href=\"' + back + '\">Browse more jobs</a>'",
    "    + '</main></body></html>';",
    "}",
    "export default async function middleware(request){",
    "  const { pathname } = new URL(request.url);",
    "  const p = pathname.endsWith('/') ? pathname : pathname + '/';",
    "  if (!/^\\/jobs\\/.+-\\d+\\/$/.test(p)) return;                 // not a job detail page -> static",
    "  const info = EXPIRED[p];",
    "  if (info) return new Response(gone(info), { status: 410, headers: { 'content-type': 'text/html; charset=utf-8' } });",
    "  if (LIVE.has(p)) return;                                       // live -> baked static page",
    "  const r = await fetch(new URL('/404.html', request.url));     // retired/unknown -> named 404",
    "  return new Response(r.body, { status: 404, headers: { 'content-type': 'text/html; charset=utf-8' } });",
    "}",
    "",
  ].join("\n");
  return head + body;
}

// Assemble a complete deployable static site in out/: baked pages + SPA assets + sitemap
// (live URLs only) + vercel.json + the edge middleware. Idempotent, so a targeted rebake
// still leaves out/ deployable. The baked landing owns out/index.html, so it is NOT copied.
async function assembleDeploy(live, expiredBack, browse){
  for (const f of ["board.html", "board.js", "landing.js", "styles.css", "404.html",
                   "favicon.ico", "icon-192.png", "apple-touch-icon.png", "og.png", "logo.png"]) await copyFile(join(SITE, f), join(OUT, f));
  for (const d of ["data", "ui", "vendor"]) await cp(join(SITE, d), join(OUT, d), { recursive: true });
  // Hand-picked brand logos live at repo-root logos/ (the user's drop folder), served from
  // /logos/ in the deploy. Same-origin, so no CSP host to allow. Cosmetic progressive
  // enhancement — skipped during bake (like favicons), copied here for the live site.
  if (existsSync(join(HERE, "..", "logos"))) await cp(join(HERE, "..", "logos"), join(OUT, "logos"), { recursive: true });

  const base = SITE_URL;
  const locs = ["/", WA_LANDER, ...browse, ...live];               // change #2: lander in sitemap; expired/retired excluded
  const xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + locs.map((u) => "  <url><loc>" + base + u + "</loc></url>").join("\n") + "\n</urlset>\n";
  await writeFile(join(OUT, "sitemap.xml"), xml, "utf8");

  // Unbaked browse routes (empty categories, jobless states) fall back to the SPA. Two
  // explicit rules — state root and sub-path with an unnamed (.*) wildcard — matching the
  // form proven in D1; a single "/:state/:rest*" did not match sub-paths on Vercel. Baked
  // pages are static files, which Vercel serves before any rewrite, so only truly-unbaked
  // browse paths reach these. /jobs/* is handled by the middleware, not here.
  // destination is /board/ (NOT /board.html): with cleanUrls+trailingSlash, /board.html
  // 308-redirects to /board/, and a rewrite whose destination redirects fails to 404.
  const states = Object.values(STATE_SLUG).join("|");
  const vercel = { cleanUrls: true, trailingSlash: true,
    rewrites: [
      { source: "/:state(" + states + ")", destination: "/board/" },
      { source: "/:state(" + states + ")/(.*)", destination: "/board/" },
    ] };
  await writeFile(join(OUT, "vercel.json"), JSON.stringify(vercel, null, 2), "utf8");
  await writeFile(join(OUT, "middleware.js"), middlewareSource(expiredBack, live), "utf8");
  return { sitemap_urls: locs.length };
}

async function bake(page, route){
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      await page.goto(route.url, { waitUntil: "domcontentloaded", timeout: 30000 });
      await page.waitForFunction(WAIT[route.type], { timeout: 20000 });
      await page.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))));
      if (route.ld) {
        await page.evaluate((html) => {
          const t = document.createElement("template"); t.innerHTML = html.trim();
          document.head.appendChild(t.content.firstChild);
        }, route.ld);
      }
      // Per-page metadata. Browse counts come from the rendered "N jobs found" on the page
      // (same source as displayed, never recomputed). Sets <title>, injects meta/canonical/
      // OG/favicon, and absolutizes the ItemList item urls the board rendered relative.
      let meta = route.meta;
      if (route.type === "browse") {
        const n = await page.evaluate(() => { const m = (document.body.textContent || "").match(/([\d,]+)\s+jobs?\s+found/i); return m ? m[1].replace(/,/g, "") : ""; });
        meta = route.state
          ? (route.category
              ? { title: PM.categoryTitle(route.category, route.state), description: PM.categoryDescription(route.category, route.state, n) }
              : { title: PM.stateTitle(route.state), description: PM.stateDescription(route.state, n) })
          : { title: "Get Hired Now - No Experience Needed | NoProbJobs", description: n + " jobs hiring now, no experience required. No sign-up, no resume, free to apply." };
      }
      if (meta) {
        const canonical = SITE_URL + route.path;
        const headHtml = PM.metaHead({ title: meta.title, description: meta.description, canonical, ogImage: SITE_URL + "/og.png" });
        await page.evaluate((title, head, base) => {
          document.title = title;
          const t = document.createElement("template"); t.innerHTML = head;
          document.head.appendChild(t.content);
          document.querySelectorAll('meta[itemprop="url"]').forEach((m) => { if (m.content && m.content.charAt(0) === "/") m.content = base + m.content; });
        }, meta.title, headHtml, SITE_URL);
      }
      const html = await page.evaluate(() => {
        // Drop the gtm.js/gtag script the GTM loader injected at render time; the static
        // loader stays and re-injects once on the client, so GTM never fires twice.
        document.querySelectorAll('script[src*="googletagmanager.com"]').forEach((el) => el.remove());
        return "<!DOCTYPE html>\n" + document.documentElement.outerHTML;
      });
      await writeBaked(route.path, html);
      return { path: route.path, type: route.type, bytes: Buffer.byteLength(html, "utf8"), ld: !!route.ld };
    } catch (e) {
      if (attempt === 1) return { path: route.path, type: route.type, error: String(e && e.message || e) };
    }
  }
}

// Serve Supabase reads from a one-time cache via request interception: without this,
// every one of the 895 standalone pages re-fetches the full jobs_list (~0.9MB) from
// Supabase (~800MB + rate-limit risk). Logo favicons are progressive enhancement (async,
// cosmetic, no baked content) and are skipped so the bake is fast and deterministic.
const CORS = { "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET,OPTIONS",
  "access-control-allow-headers": "authorization,apikey,content-type,x-client-info,accept-profile,content-profile,prefer,range",
  "access-control-max-age": "86400" };

function attachCache(page, cache){
  return page.setRequestInterception(true).then(() => {
    page.on("request", (req) => {
      const u = req.url();
      if (u.includes("/rest/v1/")) {
        // The SPA sends an Authorization header, so the browser fires a CORS preflight.
        // Answer OPTIONS with the CORS headers (not a body), or the real GET never fires.
        if (req.method() === "OPTIONS") return req.respond({ status: 204, headers: CORS });
        let body = "[]";
        if (u.includes("/jobs_list")) body = cache.list;
        else if (u.includes("/site_meta")) body = cache.meta;
        else if (u.includes("/jobs_detail")) {
          const mi = /internal_id=eq\.([^&]+)/.exec(u), mn = /job_number=eq\.(\d+)/.exec(u);
          const rec = mi ? cache.byId[decodeURIComponent(mi[1])] : (mn ? cache.byNum[mn[1]] : null);
          body = JSON.stringify(rec ? [rec] : []);
        }
        return req.respond({ status: 200, headers: Object.assign({ "content-type": "application/json" }, CORS), body });
      }
      if (/google\.com\/s2\/favicons/.test(u)) return req.abort();
      return req.continue();
    });
  });
}

// Regenerate noprobjobs/data/logos.js from the files in repo-root logos/. The runtime
// resolver (data/record.js localLogo) reads this map to show a hand-picked brand mark
// keyed on the brand slug (the file's basename), overriding the domain favicon. Adding a
// logo is one action: drop <slug>.<png|jpg|svg> into logos/ — this rebuild picks it up.
async function generateLogoIndex(){
  const dir = join(HERE, "..", "logos");
  let files = [];
  try { files = await readdir(dir); } catch { files = []; }
  const OKEXT = new Set([".png", ".jpg", ".jpeg", ".svg", ".webp"]);
  const map = {};
  for (const f of files.sort()) {
    const ext = extname(f).toLowerCase();
    if (!OKEXT.has(ext)) continue;
    map[f.slice(0, -ext.length).toLowerCase()] = f;      // basename IS the brand slug
  }
  const body = "/* GENERATED by prerender/build.mjs — do not hand-edit. Scanned from repo-root\n"
    + "   logos/. Maps a brand slug (see brandSlug in record.js) to its logo filename so the\n"
    + "   runtime knows the file + extension. Add a logo: drop <slug>.<png|jpg|svg> into logos/. */\n"
    + "export const LOGOS = " + JSON.stringify(map, null, 2) + ";\n";
  await writeFile(join(SITE, "data", "logos.js"), body, "utf8");
  return Object.keys(map);
}

async function main(){
  const t0 = Date.now();
  const logoSlugs = await generateLogoIndex();
  process.stderr.write("  logo index: " + logoSlugs.length + " brand logo(s) [" + logoSlugs.join(", ") + "]\n");
  const LIMIT = process.env.LIMIT ? +process.env.LIMIT : 0;                 // LIMIT=N: bake first N jobs
  const ONLY = process.env.ONLY ? process.env.ONLY.split(",").map((s) => s.trim()) : null;  // ONLY=n,m: bake just these job_numbers
  const SMOKE = 8;                                                          // jobs in the smoke pass
  const fullRun = !LIMIT && !ONLY;
  // The bake is INCREMENTAL — no rm(OUT). A job that crosses 30 days stops being baked
  // (skipped below), and its stale expired page stays on disk until retire.mjs deletes it;
  // that is the retire step's real work. Paths are stable (slug + job_number are write-once),
  // so live/expired pages just overwrite and nothing orphans.
  const recs = await fetchAll("/jobs_detail?select=*&limit=2000");
  const list = await fetchAll("/jobs_list?select=*&limit=2000");
  const meta = await fetchAll("/site_meta?select=pulled_at");
  const cache = { list: JSON.stringify(list), meta: JSON.stringify(meta), byId: {}, byNum: {} };
  for (const r of recs) { cache.byId[r.internal_id] = r; cache.byNum[String(r.job_number)] = r; }

  // enumerate routes
  const routes = [];
  let ldCount = 0, expiredCount = 0, retiredCount = 0;
  for (const r of recs) {
    if (r.retired) { retiredCount++; continue; }                              // retired -> not baked; retire.mjs removes any stale file
    const ld = r.expired ? null : jobPostingScript(jobPostingLd(r, COUNTRY)); // parity: no JSON-LD once expired
    if (r.expired) expiredCount++; if (ld) ldCount++;
    routes.push({ type: "job", path: jobPath(r) + "/", url: null, ld, num: r.job_number,
      meta: { title: PM.jobTitle(r), description: PM.jobDescription(r) } });
  }
  // browse: states present, and categories present within each state. state/category ride
  // on the route so bake() can build the title; the count comes from the rendered page.
  const byState = {};
  for (const r of recs) { if (!r.state) continue; (byState[r.state] = byState[r.state] || new Set()); (r.category || []).forEach((c) => byState[r.state].add(c)); }
  const browsePaths = new Set(["/jobs/"]);
  routes.push({ type: "browse", path: "/jobs/", url: null, state: null, category: null });
  for (const st of Object.keys(byState)) {
    const sp = browsePath(st, null); browsePaths.add(sp);
    routes.push({ type: "browse", path: sp, url: null, state: st, category: null });
    for (const c of byState[st]) if (CAT_SLUG[c]) { const cp = browsePath(st, c); browsePaths.add(cp); routes.push({ type: "browse", path: cp, url: null, state: st, category: c }); }
  }
  routes.push({ type: "landing", path: "/", url: null, meta: { title: PM.landingTitle(), description: PM.landingDescription() } });
  // Change #2: Washington lander. Same landing type (same render wait + meta injection), its
  // own path so bake() writes out/washington-jobs/index.html and sets canonical to itself.
  routes.push({ type: "landing", path: WA_LANDER, url: null, meta: { title: PM.waLanderTitle(), description: PM.waLanderDescription() } });

  const server = serve();
  await new Promise((r) => server.listen(PORT, r));
  const base = "http://localhost:" + PORT;
  routes.forEach((r) => { r.url = base + r.path; });
  // protocolTimeout raised from the 180s default: under a 6-wide pool a page.evaluate can
  // queue long enough to trip it on a few pages (flaky, load-dependent). 240s clears it.
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"], protocolTimeout: 240000 });

  // Circuit breaker: a failing build should die fast and loud, not grind through hundreds
  // of identical errors. Abort the moment 5 failures land in a row, or once >=10% of
  // attempted routes have failed (the percentage rule waits for a 10-route sample so a
  // lone blip can't nuke a healthy run) — whichever trips first.
  const MAX_CONSEC = 5, PCT = 0.10, PCT_FLOOR = 10;
  const breaker = { attempted: 0, fails: 0, consec: 0, done: 0, aborted: false, reason: null, firstError: null, smokeFailed: false };
  const results = [];
  async function runRoutes(list){
    let next = 0;
    const workers = Array.from({ length: CONC }, async () => {
      const page = await browser.newPage();
      await page.setViewport(MOBILE);
      await attachCache(page, cache);
      while (!breaker.aborted) {
        const i = next++; if (i >= list.length) break;
        const res = await bake(page, list[i]);
        results.push(res); breaker.attempted++; breaker.done++;
        if (res.error) {
          breaker.fails++; breaker.consec++;
          if (!breaker.firstError) {                       // surface the first failure the instant it lands
            breaker.firstError = { path: res.path, error: res.error };
            process.stderr.write("  !! FIRST FAILURE (route " + breaker.attempted + ") " + res.path + ": " + res.error + "\n");
          }
          if (breaker.consec >= MAX_CONSEC) { breaker.aborted = true; breaker.reason = MAX_CONSEC + " consecutive failures"; }
          else if (breaker.attempted >= PCT_FLOOR && breaker.fails >= breaker.attempted * PCT) { breaker.aborted = true; breaker.reason = "≥" + (PCT * 100) + "% of attempted routes failed"; }
        } else breaker.consec = 0;
        if (breaker.done % 25 === 0 || breaker.done === routes.length) {
          const el = ((Date.now() - t0) / 1000).toFixed(0);
          process.stderr.write("  " + breaker.done + "/" + routes.length + "  ok " + (breaker.done - breaker.fails) + "  failed " + breaker.fails + "  " + el + "s\n");
        }
      }
      await page.close();
    });
    await Promise.all(workers);
  }

  // Self-heal: the only failures a healthy run produces are protocolTimeout flakes — a
  // page.evaluate that queued too long behind the 6-wide pool. Re-bake the failed routes
  // ONE at a time (no pool, no contention) and swap each success back into results. What
  // still fails after this is a real error, not a flake. Runs only on a non-aborted build.
  async function healFailures(){
    const failed = routes.filter((r) => results.some((x) => x.path === r.path && x.error));
    if (!failed.length) return;
    process.stderr.write("  ~~ healing " + failed.length + " failed route(s) sequentially\n");
    const page = await browser.newPage();
    await page.setViewport(MOBILE);
    await attachCache(page, cache);
    for (const route of failed){
      const res = await bake(page, route);
      const idx = results.findIndex((x) => x.path === route.path && x.error);
      if (!res.error && idx !== -1) { results[idx] = res; breaker.fails--; process.stderr.write("  ~~ healed " + route.path + "\n"); }
      else if (res.error) process.stderr.write("  ~~ still failing " + route.path + ": " + res.error + "\n");
    }
    await page.close();
  }

  try {
    const jobRoutes = routes.filter((r) => r.type === "job");
    const nonJob = routes.filter((r) => r.type !== "job");
    if (ONLY) {
      const set = new Set(ONLY.map(String));
      await runRoutes(jobRoutes.filter((r) => set.has(String(r.num))));   // targeted rebake; no smoke/breaker gymnastics
    } else if (LIMIT) {
      await runRoutes([...jobRoutes.slice(0, LIMIT), ...nonJob]);
    } else {
      // Smoke FIRST: 8 job pages + every browse/landing route. A broken render/inject path
      // surfaces here in seconds — before the 895-page run, not as a 1.7-hour post-mortem.
      await runRoutes([...jobRoutes.slice(0, SMOKE), ...nonJob]);
      breaker.smokeFailed = results.some((r) => r.error);
      if (!breaker.smokeFailed && !breaker.aborted) await runRoutes(jobRoutes.slice(SMOKE));
    }
    if (!breaker.aborted && !breaker.smokeFailed) await healFailures();
  } finally {
    await browser.close();
    server.close();
  }

  // Lifecycle manifest — derived from the DB every run (independent of which pages were
  // baked), so a targeted rebake still leaves it complete. Drives the deploy's HTTP status
  // (expired -> 410) and the sitemap (live only). retired = a baked file that no longer has
  // a live/expired entry AND whose expiry aged out; the retire job (not this build) deletes it.
  const live = recs.filter((r) => !r.expired).map((r) => jobPath(r) + "/");
  const expired = recs.filter((r) => r.expired && !r.retired).map((r) => jobPath(r) + "/");   // 410 window (<30d)
  const retired = recs.filter((r) => r.retired).map((r) => jobPath(r) + "/");                 // retire.mjs deletes these
  const manifest = { generated: (meta[0] && meta[0].pulled_at) || null, live, expired, retired, browse: [...browsePaths] };
  await mkdir(OUT, { recursive: true });
  await writeFile(join(OUT, "_lifecycle.json"), JSON.stringify(manifest), "utf8");

  const expiredBack = {};
  for (const r of recs) if (r.expired && !r.retired) {
    // Carry the job's browse path + its category/city so the 410 page's "Get job alerts"
    // link can seed the (email-only) modal silently — the highest-intent signal on the site.
    expiredBack[jobPath(r) + "/"] = { back: backTo(r.state, r.category).href,
      cat: (r.category && r.category[0]) || null, city: r.city || null };
  }
  const deploy = await assembleDeploy(live, expiredBack, [...browsePaths]);

  const secs = (Date.now() - t0) / 1000;
  const jobs = results.filter((r) => r.type === "job");
  const failures = results.filter((r) => r.error);
  const bytes = (arr) => arr.filter((r) => r.bytes).map((r) => r.bytes);
  const avg = (a) => a.length ? Math.round(a.reduce((x, y) => x + y, 0) / a.length) : 0;
  const stopped = breaker.aborted || breaker.smokeFailed;
  const summary = {
    aborted: stopped,
    abort_reason: breaker.smokeFailed ? "smoke test failed — full run not started" : breaker.reason,
    first_error: breaker.firstError,
    routes_planned: routes.length,
    attempted: breaker.attempted,
    job_pages_ok: jobs.filter((r) => !r.error).length,
    job_pages_with_jsonld: jobs.filter((r) => r.ld).length,
    expired_no_jsonld: expiredCount,
    manifest_live: live.length,
    manifest_expired: expired.length,
    manifest_retired: retired.length,
    sitemap_urls: deploy.sitemap_urls,
    browse_pages_ok: results.filter((r) => r.type === "browse" && !r.error).length,
    landing_ok: results.filter((r) => r.type === "landing" && !r.error).length,
    failures: failures.length,
    sample_failures: failures.slice(0, 5).map((f) => ({ path: f.path, error: f.error })),
    avg_job_bytes: avg(bytes(jobs)),
    avg_browse_bytes: avg(bytes(results.filter((r) => r.type === "browse"))),
    total_build_seconds: Math.round(secs * 10) / 10,
    pages_per_second: secs > 0 ? Math.round((breaker.attempted / secs) * 10) / 10 : 0,
    concurrency: CONC,
  };
  console.log(JSON.stringify(summary, null, 2));

  // Terminal summary line in the house format ($ echo / output / one summary line), so a
  // silent bake failure can no longer read like a success. On any abort/route failure this
  // exits non-zero, which run_pull.py surfaces as STATUS: BAKE FAILED and halts the publish
  // before deploy. (Write failures throw out of main() -> the catch below -> exit 1.)
  const listingViews = summary.browse_pages_ok + summary.landing_ok;
  if (stopped || failures.length) {
    process.exitCode = 1;
    console.error("BAKE FAILED: " + summary.job_pages_ok + " job pages ok, "
      + failures.length + " route failure(s)"
      + (summary.abort_reason ? " — " + summary.abort_reason : ""));
  } else {
    console.log("BAKE COMPLETE: " + summary.job_pages_ok + " job pages, "
      + listingViews + " listing views");
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
