"""
analyze/site_data.py - the LAST pipeline step: applicable set -> the site's data.

Permanent stage, not a one-off. Every pull re-runs it:

    adapters (pull) -> normalize/enrich -> analyze/report.py (applicable.jsonl)
      -> analyze/site_data.py  ->  noprobjobs/data/jobs.js

It reads out/applicable.jsonl and writes noprobjobs/data/jobs.js with the two
exports the site loads: PULLED_AT and RECORDS. Nothing else generates that file.

THREE RULES IT ENFORCES, each a standing invariant it exists to keep:

1. MARKUP-PAGE PARITY. It emits only the fields the interface renders (FIELDS
   below - the field set the board and landing page actually read). Anything not
   on that list stays out of the payload. No internal plumbing (dedupe_hash,
   source_*, retrieved_at, schema_version, terms_reference, _tenant, ...) reaches
   the client.

2. CONDITIONAL ROWS, NO PLACEHOLDERS. A field the source did not state is OMITTED,
   not emitted as null/"". salary_min appears only when there is a salary; posted_at
   only when a date parsed. The reader never sees a hole where a value would be.
   (Booleans and the category list are structural and always emitted.)

3. first_seen NEVER SHIPS. Ordering is the data layer's job (normalize/sort_key),
   so RECORDS is emitted newest-first via freshness_order(). first_seen is the
   tier-1 sort proxy - it is NOT in FIELDS and must never be, per the prohibition
   in normalize/sort_key. The internal UNCLASSIFIED category sentinel is likewise
   mapped to [] here: it is not a real category and the site's vocabulary has no
   such chip, so it does not cross into the display layer.

Python stdlib only.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
from normalize.sort_key import freshness_order   # noqa: E402  data-layer ordering

APPLICABLE_PATH = os.path.join(ROOT, "out", "applicable.jsonl")
JOBS_JS_PATH = os.path.join(ROOT, "noprobjobs", "data", "jobs.js")

# The record -> site contract. The EXACT set the interface reads (verified against
# noprobjobs/data/record.js, ui/*.js, board.js, landing.js). Order here is the
# emit order, chosen for readability of the diff. Extend this list ONLY when a new
# field is genuinely rendered - it is the parity boundary.
FIELDS = [
    "internal_id", "company_name", "employer_domain", "title",
    "city", "state", "lat", "lng",
    "category", "experience_condition", "evidence_clauses",
    "salary_is_stated", "salary_min", "salary_max", "pay_period",
    "posted_at", "freshness_state", "employment_type", "shift_raw", "fte",
    "apply_url", "apply_class",
    "description_html",
]

# Structural fields: emitted even when falsy, because the interface branches on
# their presence/value (salary_is_stated:false is meaningful; category is an array
# the filter reads). Everything else is omitted when null/empty.
STRUCTURAL = {"internal_id", "company_name", "employer_domain", "title",
              "city", "state", "category", "experience_condition",
              "salary_is_stated", "pay_period", "freshness_state",
              "apply_url", "apply_class"}


def _empty(v):
    return v is None or v == "" or v == [] or v == {}


def project(r):
    """One applicable record -> its site-facing subset, nulls omitted."""
    out = {}
    for f in FIELDS:
        v = r.get(f)
        if f == "category":
            # drop the internal UNCLASSIFIED sentinel; it is not a display category
            v = [c for c in (v or []) if c != "UNCLASSIFIED"]
        if f in STRUCTURAL or not _empty(v):
            out[f] = v
    return out


def pulled_at(records):
    """Honest crawl date: the newest last_seen across the set (date only). This is
    what every relative label is measured against, so it must reflect the data, not
    the build clock. Derived, never hardcoded."""
    dates = [(r.get("last_seen") or "")[:10] for r in records]
    dates = [d for d in dates if d]
    return max(dates) if dates else ""


def main():
    with open(APPLICABLE_PATH, encoding="utf-8") as fh:
        recs = [json.loads(l) for l in fh if l.strip()]

    ordered = freshness_order(recs)          # newest-first, tiered; input unmutated
    at = pulled_at(recs)
    projected = [project(r) for r in ordered]

    lines = []
    lines.append(
        "/* GENERATED by analyze/site_data.py from out/applicable.jsonl - do not\n"
        "   hand-edit. Re-run that script after every pull. */\n")
    lines.append(
        "/* Date of the crawl these records came from. Every relative label\n"
        '   ("Posted yesterday") is measured against THIS, not the reader\'s clock,\n'
        "   so the wording stays true to the pull. Derived from the newest last_seen. */")
    lines.append(f'export const PULLED_AT = "{at}";\n')
    lines.append("export const RECORDS = [")
    body = ",\n".join(json.dumps(p, ensure_ascii=False) for p in projected)
    lines.append(body)
    lines.append("];")

    text = "\n".join(lines) + "\n"
    tmp = JOBS_JS_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, JOBS_JS_PATH)

    # ---- summary ----
    from collections import Counter
    print(f"wrote {JOBS_JS_PATH}")
    print(f"  PULLED_AT      {at}")
    print(f"  records        {len(projected)}")
    print(f"  bytes          {len(text.encode('utf-8')):,}")
    t0 = sum(1 for r in ordered if r.get("posted_at"))
    print(f"  with posted_at {t0} (tier 0)   without {len(ordered) - t0} (tier 1)")
    print("  per employer:")
    for emp, n in Counter(r.get("company_name") for r in ordered).most_common():
        print(f"    {n:>4}  {emp}")
    print("  category distribution (records may carry more than one; UNCLASSIFIED->[]):")
    cats = Counter()
    uncl = 0
    for p in projected:
        if not p["category"]:
            uncl += 1
        for c in p["category"]:
            cats[c] += 1
    for c, n in cats.most_common():
        print(f"    {n:>4}  {c}")
    print(f"    {uncl:>4}  (no category)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
